#!/usr/bin/env python3
"""
Безопасный autopilot для memory-wiki.

Запускает локальные deterministic-проверки и обслуживание без LLM:
graph -> health -> recall eval -> safe maintenance. Предназначен для ручного
запуска, cron, Windows Task Scheduler или другого планировщика.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path


DEFAULT_MEMORY_ROOT = Path(
    os.environ.get(
        "HERMES_MEMORY_ROOT",
        os.environ.get("AI_MEMORY_ROOT", str(Path.home() / "Hermes_Memory")),
    )
)


def run_step(label: str, command: list[str], log_lines: list[str]) -> int:
    """Запускает шаг и пишет краткий лог."""
    print(f"=== {label} ===")
    print(" ".join(command))
    completed = subprocess.run(command, text=True, capture_output=True)
    output = completed.stdout.strip()
    error = completed.stderr.strip()
    if output:
        print(output)
    if error:
        print(error)
    status = "OK" if completed.returncode == 0 else f"ERROR {completed.returncode}"
    log_lines.extend([
        f"## {label}",
        "",
        f"Status: {status}",
        "",
        "```text",
        output[-4000:] if output else "",
        error[-2000:] if error else "",
        "```",
        "",
    ])
    return completed.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="Run safe memory-wiki autopilot")
    parser.add_argument("--memory-root", default=str(DEFAULT_MEMORY_ROOT), help="Корень памяти")
    parser.add_argument("--dry-run", action="store_true", help="Проверить без записи maintenance-изменений")
    parser.add_argument("--skip-maintenance", action="store_true", help="Не запускать memory-maintain")
    parser.add_argument("--skip-eval", action="store_true", help="Не запускать recall eval")
    args = parser.parse_args()

    print("=== Memory autopilot ===")
    memory_root = Path(args.memory_root)
    tools_dir = memory_root / "knowledge-base" / "tools"
    report_dir = memory_root / "knowledge-base" / "state" / "reports"
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    log_path = report_dir / f"memory-autopilot-{stamp}.md"

    log_lines = [
        "# Memory Autopilot Report",
        "",
        "status: active",
        f"last_updated: {datetime.now().date().isoformat()}",
        "",
        "## Summary",
        "",
        f"- Dry run: {args.dry_run}",
        f"- Memory root: `{memory_root}`",
        "",
    ]

    commands = [
        ("Timeline", [sys.executable, str(tools_dir / "memory-timeline.py"), "--memory-root", str(memory_root)]),
        ("Graph", [sys.executable, str(tools_dir / "memory-graph.py"), "--memory-root", str(memory_root)]),
        ("Health", [sys.executable, str(tools_dir / "memory-health.py"), "--memory-root", str(memory_root)]),
    ]
    if args.dry_run:
        for _, command in commands:
            command.append("--dry-run")
    if not args.skip_eval:
        eval_command = [sys.executable, str(tools_dir / "memory-recall-eval.py"), "--memory-root", str(memory_root)]
        if args.dry_run:
            eval_command.append("--dry-run")
        commands.append(("Recall eval", eval_command))
    if not args.skip_maintenance:
        maintain_command = [sys.executable, str(tools_dir / "memory-maintain.py"), "--all", "--memory-root", str(memory_root)]
        if args.dry_run:
            maintain_command.append("--dry-run")
        commands.append(("Safe maintenance", maintain_command))

    codes = []
    for label, command in commands:
        codes.append(run_step(label, command, log_lines))

    worst = max(codes) if codes else 0
    log_lines.extend([
        "## Provenance",
        "",
        "- Generated by `memory-autopilot.py`.",
        "",
    ])
    if args.dry_run:
        print(f"[DRY-RUN] Autopilot report would be written: {log_path}")
    else:
        report_dir.mkdir(parents=True, exist_ok=True)
        log_path.write_text("\n".join(log_lines), encoding="utf-8")
        print(f"[OK] Autopilot report: {log_path}")
    print("=== Готово ===")
    return worst


if __name__ == "__main__":
    raise SystemExit(main())

